feature/v1-046/Learning course - video
k-krasilnikova/SUL pull request #104
Opened 2022-01-28 14:38 UTC by Julia-Maliutsina

Implemented:
1. React video player with custom play button.
2. Function to define type of material: text or video.
3. API connection: mock course material replaced with data from server.

2022-01-28 15:24 UTC, hauteballe requested changes

2022-01-28 15:24 UTC, hauteballe commented on frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
> +  const maxStage = data ? data.course.materials.length : 1;
Please remove magic number

2022-01-28 17:10 UTC, hauteballe submitted a review, later dismissed

2022-01-31 10:09 UTC, k-krasilnikova requested changes

2022-01-31 10:09 UTC, k-krasilnikova commented on frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
> +  ) : null;
Remove please `null` We shouldn't allow such logic

2022-01-31 10:09 UTC, k-krasilnikova commented on frontend/src/pages/LearningCourse/LearningCourse.tsx
> +  return (
It's an arrow function!
Remove please `return` statement

2022-01-31 10:09 UTC, k-krasilnikova commented on frontend/src/api/myCourses/getMyCourseInfo.ts
> +  _id: string | undefined,
```suggestion
  _id?: string,
```

2022-02-01 10:16 UTC, k-krasilnikova approved these changes

2022-02-01 10:16 UTC, merged