[WIP]V1-067 feat: implement passing the test
k-krasilnikova/SUL pull request #135
Opened 2022-02-07 10:23 UTC by hauteballe

**Overview:**
1. Implemented getCourseTest request
2. Implemented Passing test and Test Result pages with default data from /constants (will be changed in V1-073)
     Type of Test Result page (completed/failed) can be changed manually now by changing this line: 
     `const STATUS = TEST_STATUSES.completed;` in TestResultContainer
3. Added custom styles for radio buttons according to mockup

2022-02-07 14:37 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-02-08 08:51 UTC, k-krasilnikova requested changes

2022-02-08 08:51 UTC, k-krasilnikova commented on frontend/src/pages/PassingTest/QuestionItem/QuestionItem.tsx
> +      <TestQuestion>{questionItem ? questionItem.question : null}</TestQuestion>
```suggestion
      {questionItem && <TestQuestion>{questionItem.question}</TestQuestion>}
```

2022-02-08 08:51 UTC, k-krasilnikova commented on frontend/src/pages/PassingTest/TestResult/TestResult.tsx
> +              trailColor="#eaeaea"
It should be defined inside ProgressBar, we shouldn't provide styles by props

2022-02-08 08:51 UTC, k-krasilnikova commented on frontend/src/pages/PassingTest/TestResult/TestResult.tsx
> +                </>
Do we really need this mocks? Maybe it will be better to use from API response?

2022-02-08 16:53 UTC, closed without merging