Responsive profile page
k-krasilnikova/SUL pull request #19
Opened 2021-12-24 14:10 UTC by Julia-Maliutsina

Overview:
Profile page with avatar component and the list of user's data. 
The size of elements, of font and spaces change depending on the window width.

2021-12-27 11:18 UTC, k-krasilnikova requested changes
Good job! But some changes required.

2021-12-27 11:18 UTC, k-krasilnikova commented on frontend/src/components/Avatar/image/avatarDefault.svg
> +</svg>
Move please this file into `src/icons`. All the svg/png files will be stored here

2021-12-27 11:18 UTC, k-krasilnikova commented on frontend/src/components/Avatar/image/avatarDefault.svg
> +</svg>
And leave index inside this folder src/images!
It's a good practice, good job!

2021-12-27 11:18 UTC, k-krasilnikova commented on frontend/src/pages/Profile/Profile.tsx
> +import { UserAvatar } from 'components/Avatar';
Empty line between different import types please!

2021-12-27 11:34 UTC, hauteballe approved these changes

2021-12-27 13:28 UTC, hauteballe approved these changes

2021-12-28 08:04 UTC, k-krasilnikova approved these changes

2021-12-28 08:04 UTC, merged