feat: implement menu according to the role (V1-015)
k-krasilnikova/SUL pull request #22
Opened 2021-12-27 14:45 UTC by hauteballe

**Overview:**

1. Implement Menu according to Role of the client
2. Add Employees, Requests and Skills pages
3. Change index.ts in components folders for better readability

2021-12-27 15:05 UTC, Julia-Maliutsina submitted a review, later dismissed

2021-12-28 08:22 UTC, k-krasilnikova requested changes
Good job, but some changes required

2021-12-28 08:22 UTC, k-krasilnikova commented on frontend/src/components/layout/Menu/MenuContainer.tsx
> +export const menuItems = ROLES_MENU['employee'];
Remove please export. We can't export anything except container inside container file. And also we shouldn't import inside component anything from its container(imports hell)
Move please all the uppercase constants to the constants folder.
Let's define Container like:
```
const MenuContainer: React.FC = () => {
  const menuItems = ROLES_MENU['employee'];

  return <Menu menuList={menuItems}/>;
}
```

2021-12-29 11:05 UTC, k-krasilnikova approved these changes

2021-12-29 11:05 UTC, merged