bugfix/fixed search & filter styles
k-krasilnikova/SUL pull request #224
Opened 2022-03-02 21:15 UTC by Julia-Maliutsina

2022-03-03 08:51 UTC, k-krasilnikova requested changes

2022-03-03 08:51 UTC, k-krasilnikova commented on frontend/src/components/Layout/Header/styled.ts
> +  [theme.breakpoints.down(950)]: {
Return it please

2022-03-03 08:51 UTC, k-krasilnikova commented on frontend/src/components/Layout/MobileSearch/styled.ts
> +  [theme.breakpoints.up(950)]: {
replace to 'md'

2022-03-07 08:57 UTC, k-krasilnikova commented
Resolve conflicts please!

2022-03-07 18:58 UTC, irina-sinitsyna approved these changes

2022-03-10 09:07 UTC, closed without merging