Bugfix V1-096 "Completed" button on the course card
k-krasilnikova/SUL pull request #229
Opened 2022-03-04 08:51 UTC by irina-sinitsyna

**Overview:** 
1. Added "Completed" button on My Courses page in case client course status is "completed"

2022-03-04 10:21 UTC, NikitaKhadnevich submitted a review, later dismissed
I will update my pull request according these changes

2022-03-04 10:25 UTC, k-krasilnikova requested changes

2022-03-04 10:25 UTC, k-krasilnikova commented on frontend/src/pages/MyCourses/styled.ts
> +  },
```suggestion
    height: '50px',
    width: '150px',
    marginRight: '40px !important',
    fontSize: '18px!important',
    lineHeight: '22px',
    padding: '12px 12px!important',
    justifySelf: 'flex-start',
    alignSelf: 'center',
    display: 'flex',
  [theme.breakpoints.down('lg')]: {
    height: '44px',
    width: '121px',
    marginRight: '36px !important',
    fontSize: '14px!important',
    lineHeight: '19px',
    padding: '10px 0px !important',
  },
```

2022-03-04 15:15 UTC, NikitaKhadnevich approved these changes
Done it

2022-03-07 09:00 UTC, k-krasilnikova approved these changes

2022-03-07 09:00 UTC, merged