bug/v1-099
k-krasilnikova/SUL pull request #245
Opened 2022-03-10 13:04 UTC by Julia-Maliutsina

2022-03-10 13:46 UTC, irina-sinitsyna requested changes

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
> +        if (searchInputValue.length > 0) {
Remove magic number please

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
> +            enqueueSnackbar('Something went wrong');
Here you should also add snackbar type(successSnackbar or errorSnackbar) from constants/snackbarVariant and also move the message to this file too
So you will have something like that: `enqueueSnackbar(errorSnackbarMessage.failed, errorSnackbar);`

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
> +      const formattedValue = event.target.value.split(/\s+/).join(' ').trimStart().trimEnd();
I think we should move it to helpers

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
> +    if (!formattedKey && searchInputValue.length === 0) {
Magic number and looks like a helper again

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
> +            enqueueSnackbar('Something went wrong');
Please change it according to previous comment

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
> +        if (searchInputValue.length > 0) {
Magic number

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
> +      const formattedValue = event.target.value.split(/\s+/).join(' ').trimStart().trimEnd();
Helpers?

2022-03-10 13:46 UTC, irina-sinitsyna commented on frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
> +    const formattedKey = key.trim();
Magic number and looks like a helper again

2022-03-10 16:43 UTC, k-krasilnikova commented on frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
> +        if (searchInputValue.length > 0) {
```suggestion
        if (searchInputValue.length) {
```

2022-03-10 17:23 UTC, irina-sinitsyna approved these changes

2022-03-11 08:31 UTC, k-krasilnikova approved these changes

2022-03-11 08:31 UTC, merged