bug/v1-117/fixed starting test & continue learning
k-krasilnikova/SUL pull request #265
Opened 2022-03-16 20:01 UTC by Julia-Maliutsina

2022-03-16 22:50 UTC, irina-sinitsyna approved these changes

2022-03-17 10:45 UTC, k-krasilnikova requested changes

2022-03-17 10:45 UTC, k-krasilnikova commented on frontend/src/api/myCourses/startClientCourse.ts
> +      if (courseResponse?.status === 'approved') {
Reuse please from contant `COURSE_STATUSES`

2022-03-17 12:01 UTC, Julia-Maliutsina commented on frontend/src/api/myCourses/startClientCourse.ts
> +      if (courseResponse?.status === 'approved') {
Done

2022-03-17 12:16 UTC, k-krasilnikova commented
Conflicts :(

2022-03-17 13:01 UTC, merged