bugfix/v1-070/fixed courses ui bugs
k-krasilnikova/SUL pull request #288
Opened 2022-03-21 13:14 UTC by Julia-Maliutsina

Fixed some bugs on cutting course description to a certain length, font sizes and course cards sizes and margins.

2022-03-22 08:42 UTC, irina-sinitsyna submitted a review, later dismissed

2022-03-22 10:07 UTC, ostapdans99 requested changes

2022-03-22 10:46 UTC, Julia-Maliutsina commented on frontend/src/components/Course/Course.tsx
> +            variant={
fixed

2022-03-22 10:46 UTC, Julia-Maliutsina commented on frontend/src/components/Course/Course.tsx
> +            text={
fixed

2022-03-22 11:43 UTC, k-krasilnikova commented on frontend/src/components/Course/Course.tsx
> +            text={
I still can't see calculating in constant..
Where you moved it?

2022-03-22 20:28 UTC, Julia-Maliutsina commented on frontend/src/components/Course/Course.tsx
> +            text={
Moved to constant inside CourseContainer.

2022-03-23 06:21 UTC, ostapdans99 approved these changes

2022-03-23 12:29 UTC, k-krasilnikova approved these changes

2022-03-23 12:30 UTC, merged