[WIP]fix/V1-143 - Progress bar on details page
k-krasilnikova/SUL pull request #292
Opened 2022-03-22 11:44 UTC by zhuk-vezunchikz

2022-03-22 13:29 UTC, k-krasilnikova requested changes

2022-03-22 13:32 UTC, irina-sinitsyna requested changes

2022-03-22 13:32 UTC, irina-sinitsyna commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +import { COMPLETED_STATUS_TEXT, FAILED_STATUS_TEXT } from '../../constants/detailedCourse';
Please use absolute paths here for constants and fix imports order after it

2022-03-22 14:00 UTC, zhuk-vezunchikz commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +        progressVariant = VARIANTS.failed;
done

2022-03-22 14:03 UTC, irina-sinitsyna commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +import convertStatusToProgress from 'utils/helpers/convertStaatusToProgress';
`import convertStatusToProgress from 'utils/helpers/convertStatusToProgress';`

2022-03-22 14:11 UTC, zhuk-vezunchikz commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +import convertStatusToProgress from 'utils/helpers/convertStaatusToProgress';
done

2022-03-22 14:13 UTC, irina-sinitsyna submitted a review, later dismissed

2022-03-22 14:20 UTC, irina-sinitsyna submitted a review, later dismissed

2022-03-22 20:30 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-03-23 12:31 UTC, k-krasilnikova requested changes

2022-03-23 12:31 UTC, k-krasilnikova commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +  }
Move this check to the useEffect, it will help us to avoid an additional render

2022-03-28 13:10 UTC, merged