Bug/v1 140 | Fixed long skill names going out of the border & added hover to showing full skill name
k-krasilnikova/SUL pull request #306
Opened 2022-03-24 11:44 UTC by PechurinaLena

2022-03-24 12:32 UTC, irina-sinitsyna requested changes

2022-03-24 12:32 UTC, irina-sinitsyna commented on frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
> +  const [isShown, setIsShown] = useState(false);
Please move to SkillUserContainer and remove return statement, here shouldn't be any logic

2022-03-24 12:32 UTC, irina-sinitsyna commented on frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
> +        <div style={{ position: 'relative' }}>
Please use styled.ts for styling components

2022-03-24 12:32 UTC, irina-sinitsyna commented on frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
> +          <div style={{ width: '70px' }}>
Like the previous one

2022-03-24 12:32 UTC, irina-sinitsyna commented on frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
> +              onMouseEnter={() => setIsShown(true)}
Maybe you should create separate functions (in SkillsInfoContainer) and reuse them here like this:
`onMouseEnter={showSkillInfo}`

2022-03-24 12:32 UTC, irina-sinitsyna commented on frontend/src/pages/Profile/UserSkills/SkillInfo.tsx
> +              onMouseLeave={() => setIsShown(false)}
Like the previous one

2022-03-25 09:29 UTC, irina-sinitsyna approved these changes

2022-03-25 14:58 UTC, Julia-Maliutsina approved these changes

2022-03-28 07:46 UTC, merged