feature/V1-026
k-krasilnikova/SUL pull request #31
Opened 2022-01-03 10:49 UTC by zhuk-vezunchikz

2022-01-03 12:27 UTC, k-krasilnikova submitted a review, later dismissed

2022-01-03 12:38 UTC, SaXaPhonist requested changes

2022-01-03 12:38 UTC, SaXaPhonist commented on backend/src/db/models/ClientCourses.ts
> +});
client course no need to have title, description,technology and other field that comes from "Courses" collection as all you need it's to have a ref to "Course collection", in client course we should controll progress of taken courses  and other control over the course

2022-01-05 08:59 UTC, k-krasilnikova approved these changes

2022-01-05 08:59 UTC, merged