bugfix/v1-100/fixed learning page styles
k-krasilnikova/SUL pull request #312
Opened 2022-03-25 13:38 UTC by Julia-Maliutsina

Fixed according to QA:
1. Video container, it's preview, play icon.
2. Start the test button.
3. Comments label display for Safari.

2022-03-25 13:40 UTC, irina-sinitsyna submitted a review, later dismissed

2022-03-28 07:49 UTC, k-krasilnikova requested changes

2022-03-28 07:49 UTC, k-krasilnikova commented on frontend/src/pages/LearningCourse/styled.ts
> +    padding: '0 !important',
Remove all the "important" marks

2022-03-28 07:49 UTC, k-krasilnikova commented on frontend/src/pages/LearningCourse/styled.ts
> +    display: 'none !important',
!

2022-03-28 11:24 UTC, Julia-Maliutsina commented on frontend/src/pages/LearningCourse/styled.ts
> +    display: 'none !important',
Removed

2022-03-28 11:24 UTC, Julia-Maliutsina commented on frontend/src/pages/LearningCourse/styled.ts
> +    padding: '0 !important',
Removed

2022-03-29 08:17 UTC, merged