Feature/v1-176 | FE & BE paths refactored.
k-krasilnikova/SUL pull request #360
Opened 2022-04-04 16:35 UTC by dapodev

2022-04-04 19:33 UTC, irina-sinitsyna submitted a review, later dismissed

2022-04-05 09:15 UTC, k-krasilnikova requested changes

2022-04-05 09:15 UTC, k-krasilnikova commented on frontend/src/components/Layout/Header/SearchCourses/SearchResultItem.tsx
> +        : transformRoute(PATHS.courseDetails, course._id)
Move please this condition before return statement of this component and define as constant

2022-04-05 09:28 UTC, irina-sinitsyna approved these changes

2022-04-05 09:39 UTC, k-krasilnikova approved these changes

2022-04-05 09:40 UTC, merged