Improve/v1-187 | Fixed secure of pages depends on user roles
k-krasilnikova/SUL pull request #374
Opened 2022-04-07 09:14 UTC by PechurinaLena

2022-04-07 09:32 UTC, k-krasilnikova requested changes

2022-04-07 12:30 UTC, ostapdans99 commented on frontend/src/components/AuthRoute/AuthRoute.tsx
> +};
Maybe will be better
```suggestion
const RoleRoute = ({ path, element, roles }) => {
  const { data: userProfileResponse } = useGetProfile();

  const isAllowed = roles.includes(userProfileResponse?.role as ROLE);

  return isAllowed ? <Route path={path} element={element}> : <Navigate to={PATHS.notFound} />;
};

export default RoleRoute;
```

2022-04-07 12:30 UTC, ostapdans99 commented on frontend/src/App.tsx
> +            />
```suggestion
       <RoleRoute element={<SkillsMap />} path={PATHS.skillsMap} roles={[ROLE.employee]} />
```

2022-04-11 05:57 UTC, ostapdans99 approved these changes

2022-04-11 09:48 UTC, k-krasilnikova approved these changes

2022-04-11 09:48 UTC, merged