fix/V1-177 - fix searching
k-krasilnikova/SUL pull request #399
Opened 2022-04-13 15:08 UTC by zhuk-vezunchikz

- Fix problems with incorrect display of the course selected in the search
- Added closing of search results when choosing a course
- Added clearing of search field when choosing a course

2022-04-13 15:19 UTC, irina-sinitsyna requested changes

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResult.tsx
> +  handleSearchClose: () => void;
order

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResult.tsx
>  interface CoursesFound {
```suggestion
interface ICoursesFound {
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResult.tsx
> +import { IClientCourseIds } from './types';
```suggestion
import { IClientCourseId } from './types';
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
>  import React, { useEffect, useState } from 'react';
```suggestion
import { useEffect, useState } from 'react';
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
> +interface Props {
```suggestion
interface IProps {
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
> +interface Props {
also shouldn't it be moved to ./types ?

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
>    const { data: clientCourses } = useSearchClientCourses();
```suggestion
  const { data: clientCoursesResponse } = useSearchClientCourses();
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
>    const { data: clientCourses } = useSearchClientCourses();
or clientCoursesData

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItem.tsx
> +  handleSelectFoundCourse: (event: React.MouseEvent<HTMLElement>) => void;
order

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItemContainer.tsx
>  interface CoursesFound {
```suggestion
interface ICoursesFound {
```

2022-04-13 15:19 UTC, irina-sinitsyna commented on frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItemContainer.tsx
> +  handleSearchClose: () => void;
order

2022-04-14 07:53 UTC, k-krasilnikova approved these changes

2022-04-14 07:53 UTC, merged