Feature/v1-193 | Implemented opportunity to get employee's available courses.
k-krasilnikova/SUL pull request #410
Opened 2022-04-18 09:37 UTC by dapodev

# Overview 

New endpoint implemented. Some utils added, some refactored.

# Changes

1. New API endpoint `[GET] /api/employees/:id/courses/available?title=jq` where `:id` is employee's id and `title` is query parameter to filter courses by their title if necessary. *NO PAGINATION*
2. Compare `ObjectId` util refactored so to allow compare ids with passing one or both `string` values.
3. Implemented available courses filter util and normalizer.
4. Implemented new provider to get courses with statuses without pagination.

2022-04-20 10:13 UTC, SaXaPhonist requested changes

2022-04-20 10:46 UTC, dapodev commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
No Pagination is here

2022-04-20 10:47 UTC, dapodev commented on backend/src/utils/normaliser/courses.ts
> +const filterOnlyAvailableCourses = (courses: ICourseStatus[]): ICourseStatus[] =>
ICourseStatus is common course with `status` field

2022-04-20 10:47 UTC, dapodev commented on backend/src/utils/normaliser/courses.ts
> +const filterOnlyAvailableCourses = (courses: ICourseStatus[]): ICourseStatus[] =>
If status exists of course

2022-04-20 10:53 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
but paggination in our getCourses is also odd

2022-04-20 10:54 UTC, SaXaPhonist commented on backend/src/utils/normaliser/courses.ts
> +const filterOnlyAvailableCourses = (courses: ICourseStatus[]): ICourseStatus[] =>
rename to coursesWithStatus

2022-04-20 11:04 UTC, dapodev commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
It's not optional 😄

2022-04-20 11:07 UTC, dapodev commented on backend/src/utils/normaliser/courses.ts
> +const filterOnlyAvailableCourses = (courses: ICourseStatus[]): ICourseStatus[] =>
done

2022-04-20 11:13 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
![image](https://user-images.githubusercontent.com/73477329/164218592-a41208c1-8a35-4222-b8b3-1bc116274d3b.png)
 if "0" it return all courses

2022-04-20 11:39 UTC, dapodev commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
But it still requires pageSize 😄. And its not a good way to provide page size = 100000000000 or calculate it in advance

2022-04-20 12:37 UTC, SaXaPhonist requested changes

2022-04-20 12:37 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
ok, what if default of limit will be 0? it should return all existed docs

2022-04-20 17:05 UTC, dapodev commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
doesnt work. https://screencast-o-matic.com/i/c3fYbfVY2cR

2022-04-21 08:14 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
i believe that there are some solutions, for example just first one: 
![image](https://user-images.githubusercontent.com/73477329/164410588-1b1c3a38-78fa-495d-8e5c-a520aef4899a.png)

2022-04-21 10:07 UTC, SaXaPhonist requested changes

2022-04-21 10:07 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const getAllCoursesProvider = async (userId: string, title?: string): Promise<ICourseStatus[]> => {
you could move this populated fn out of provider

2022-04-22 08:57 UTC, closed without merging