V1-163 Creating course endpoint
k-krasilnikova/SUL pull request #416
Opened 2022-04-18 14:09 UTC by zhuk-vezunchikz

Created functionality for creating course on backend side

2022-04-18 16:06 UTC, dapodev requested changes

2022-04-18 16:06 UTC, dapodev commented on backend/src/controllers/admin/preparingCourseData.ts
> +    courseDataToSave.title = courseDataFromRequest.title;
Validation required

2022-04-18 16:06 UTC, dapodev commented on backend/src/controllers/admin/preparingCourseData.ts
> +    courseDataToSave.complexity = courseDataFromRequest.complexity;
validation required

2022-04-18 16:06 UTC, dapodev commented on backend/src/controllers/admin/preparingCourseData.ts
> +import { NextFunction, Request, Response } from 'express';
And move, pls, all the validations to one huge util. And add `throw` to its parts, so to send error to frontend if any validation is not performed successfully.

2022-04-18 16:06 UTC, dapodev commented on backend/src/controllers/admin/addCourse.ts
> +    const newCourse = res.locals.results;
We should store as the locals.results value that provider returns after creating new document!

2022-04-20 08:27 UTC, dapodev requested changes

2022-04-20 08:27 UTC, dapodev commented on backend/src/db/providers/skillProvider.ts
> +  });
Make it one-line arrow function pls, if it has only return statement and nothing more

2022-04-20 08:27 UTC, dapodev commented on backend/src/db/providers/testProvider.ts
> +};
You should only create test here. All the other actions should be done outside provider. Move setting proper numbers to questions outside provider, pls

2022-04-20 08:27 UTC, dapodev commented on backend/src/utils/validation/isValidComplexity.ts
> +import { UserRank } from '../../enums/users';
absolute import

2022-04-20 08:27 UTC, dapodev commented on backend/src/utils/validation/isValidComplexity.ts
> +  Boolean(complexity && typeof complexity === 'number');
not enough checks. complexity also should be positive and should contain only those values, that described in `UserRank` enum. That is really important for some other logic parts of our api

2022-04-20 08:27 UTC, dapodev commented on backend/src/utils/validation/isValidCourseData.ts
> +};
That's nor really good. Pls, call every validation separately and throw an error, that show what actually was wrong. Example: if description is invalid, the message should be "Course description was not validated successfully." or "Invalid course description."

2022-04-20 08:27 UTC, dapodev commented on frontend/src/api/myCourses/searchClientCourses.ts
> +    { cacheTime: 900000 },
Not related to ticket, but whatever. Magic number is not a good practice.

2022-04-20 10:49 UTC, SaXaPhonist requested changes

2022-04-20 10:49 UTC, SaXaPhonist commented on backend/src/db/providers/skillProvider.ts
> +const skillsToCourseTechs = async (technologies: { skill: ObjectId; points: number }[]) => {
"getSkillsToCourseTechs"

2022-04-20 10:49 UTC, SaXaPhonist commented on backend/src/db/providers/skillProvider.ts
> +      return SkillModel.findOne({ name: skill });
it's not quite clear for me how you search by name ( string in model) with { skill } that is equal to Objectid

2022-04-20 10:49 UTC, SaXaPhonist commented on backend/src/db/providers/skillProvider.ts
> +      return SkillModel.findOne({ name: skill });
i consider that you can move this promise all out to controller and use instead this provider provider "getCommonSkill"

2022-04-21 14:47 UTC, dapodev approved these changes

2022-04-22 06:50 UTC, merged