Bug/v1-187 | Fixed RoleRoute after reloading the page
k-krasilnikova/SUL pull request #430
Opened 2022-04-22 07:30 UTC by PechurinaLena

Fixed bug where no-founded page was displayed after reloading the page

2022-04-22 07:45 UTC, irina-sinitsyna requested changes

2022-04-22 07:45 UTC, irina-sinitsyna commented on frontend/src/components/Routes/RoleRoute.tsx
> +  const isPageReloaded = window.performance && window.performance.navigation.type === 1;
please remove magic number

2022-04-22 07:45 UTC, irina-sinitsyna commented on frontend/src/components/Routes/RoleRoute.tsx
> +import { IRoleRouteProps } from './types';
imports order

2022-04-22 07:45 UTC, irina-sinitsyna commented on frontend/src/components/Routes/RoleRoute.tsx
> +  return isAllowed || isPageReloaded ? <>{children}</> : <Navigate replace to="/not-found" />;
```suggestion
  return isAllowed || isPageReloaded ? <>{children}</> : <Navigate replace to={PATHS.notFound} />;
```

2022-04-22 07:45 UTC, irina-sinitsyna commented on frontend/src/components/Routes/types.ts
> +import { Role } from 'constants/menuRoles';
imports order

2022-04-22 07:55 UTC, irina-sinitsyna commented on frontend/src/components/Routes/types.ts
> +import { Role } from 'constants/menuRoles';
also please create a folder types with index.ts inside instead of types.ts

2022-04-23 09:09 UTC, ostapdans99 approved these changes

2022-04-23 14:10 UTC, irina-sinitsyna approved these changes

2022-04-26 06:26 UTC, merged