Feature/v1-158 | Fixed issues that founded while testing
k-krasilnikova/SUL pull request #446
Opened 2022-04-27 12:08 UTC by PechurinaLena

1. **Fixed**:  font-size of the "Search" should be the same as in the top bar
2. **Fixed**: The label under the name of the skill on the skill card should be removed (because its not using right now)
3. **Fixed**:  If the first letter of the skill is the same as the first letter of the category, the skill will not be displayed in the search result (if you enter only one letter), if you enter more letters, the skill will be displayed
_**Resolve method**_ - added condition to specify search, result will be displayed only after user types 2 or more symbols
4. **Fixed**: if the skill name has a long words, these words should be cut off with dots. And when the user is hovering the mouse, the full name should be displayed
Added a logic with a showing full skillName when the user hover on the name

2022-04-27 19:59 UTC, zhuk-vezunchikz commented on frontend/src/components/SkillGroup/SkillItem/SkillItemContainer.tsx
> +  };
Do we really need two of these functions? Can we pass "setSkillNameShown" to the component at once and thus replace two props with one? What do you think?

2022-04-28 11:39 UTC, irina-sinitsyna requested changes

2022-04-28 11:39 UTC, irina-sinitsyna commented on frontend/src/pages/Skills/SkillsContainer.tsx
> +    if (debouncedSearchValue && debouncedSearchValue.length >= 2) {
magic number

2022-04-28 11:39 UTC, irina-sinitsyna commented on frontend/src/pages/Skills/SkillsContainer.tsx
> +    if (debouncedSearchValue && debouncedSearchValue.length >= 2) {
and should we check both of these conditions? or maybe debouncedSearchValue.length will be enough?

2022-04-29 10:17 UTC, irina-sinitsyna approved these changes

2022-04-29 10:32 UTC, ostapdans99 approved these changes

2022-04-29 12:23 UTC, merged