Feature/v1-219 | Implement scheduler for updating test statuses.
k-krasilnikova/SUL pull request #479
Opened 2022-05-11 10:59 UTC by dapodev

# Overview

Implemented scheduler that starts it's job every day at 7 AM and updates statuses of client courses from `failed` to `started` if `disable test time` expired.

# Changes
1. Implemented scheduler using `node-cron`.
2. Refactored db connection.

2022-05-11 15:32 UTC, SaXaPhonist requested changes

2022-05-11 15:32 UTC, SaXaPhonist commented on backend/src/utils/schedule/constants.ts
> +  } as const,
why do you need here 2 "as const"

2022-05-12 07:07 UTC, dapodev commented on backend/src/utils/date/testDate.ts
>  /**
I'll remove it

2022-05-12 07:08 UTC, dapodev commented on backend/src/middlewares/connectionMiddleware.ts
> -    const DB_URL: Record<string, string | undefined> = {
I don't think we should copy/paste this code among the project. I will leave it that way

2022-05-12 07:17 UTC, dapodev commented on backend/src/utils/schedule/constants.ts
> +  } as const,
removed

2022-05-12 11:39 UTC, SaXaPhonist approved these changes

2022-05-12 11:59 UTC, merged