Feature/lessons and test steps
k-krasilnikova/SUL pull request #486
Opened 2022-05-16 11:53 UTC by PechurinaLena

Added Lesson Step components
Added Test Step components (not finished because we do not have backend endpoint for test)
Added styles for components

2022-05-16 13:43 UTC, irina-sinitsyna requested changes

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/TestStep/TestItem/styled.ts
> +  justifyContent: 'end',
order

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/types.ts
> +}
it's the same as IStepProps

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/types.ts
> +  id: number;
order

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
> +
wrong UI
<img width="705" alt="image" src="https://user-images.githubusercontent.com/44285339/168602847-ca69a76b-210e-474c-86dc-ae8e20ea21c2.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/44285339/168602892-bc77fdaf-7c1a-473a-a24e-569a360fe630.png">

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
> +
also in case of removing 2nd lesson, the # of next lesson should be 2 not 3

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
> +
add more lessons button is not working, blank page appears

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
> +
why all the fields have different font styles and size?

2022-05-16 13:43 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts
> +
not all the values changes in formik values, please fix it and provide proper structure

2022-05-17 18:21 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
> +                  ? `${Titles.videUrlTitle}`
typo

2022-05-17 18:22 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
> +                  <LessonButton variant="mediumOutlined" onClick={() => push(material)}>
why not empty object?

2022-05-17 18:27 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/TestStep/TestItem/TestItem.tsx
>  const TestItem: FC<ITestItemProps> = ({ formik, handleChangeAnswer, isCurrentAnswer }) => (
Please check this one: https://formik.org/docs/examples/radio-group
I suppose, you don't need to use `isCurrentAnswer` useState here

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
> +    <LessonItemWrapper>
no need to use return here

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
> +        {Titles.lessonCount} {index + 1}
magic number (please move to constants)

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx
> +          {LESSONS_TYPE.map((option) => (
let's replace `option` with something more descriptive (type / typeOption ? )

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
>      {courseData &&
please add a loader here as in skills and definition steps

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonsStepContainer.tsx
> +);
so we don't need Container if we don't have any logic here. please remove it

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/LessonsStep/LessonsStepContainer.tsx
> +);
and don't forget to change an export in index.ts

2022-05-26 08:52 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/types.ts
> +    exercise?: { eN: number; title: string; task: string; code: string };
should be improved as you have 2 similar interfaces

2022-05-26 08:53 UTC, irina-sinitsyna commented on frontend/src/pages/CourseEditor/CourseEditor.tsx
> +const CourseEditor: React.FC<ICourseEditorProps> = ({ courseData, ...props }) => (
pleace remove React here

2022-06-02 08:26 UTC, ostapdans99 commented on frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
> +        formik.values.technologies.map((technology, index) => (
map should be inside FieldArray

2022-06-02 13:09 UTC, irina-sinitsyna approved these changes

2022-06-02 13:30 UTC, dapodev approved these changes

2022-06-02 13:58 UTC, merged