feature/V1-027
k-krasilnikova/SUL pull request #50
Opened 2022-01-13 15:13 UTC by zhuk-vezunchikz

- Created migration for client courses
- Created endpoint for applying courses

2022-01-13 15:42 UTC, SaXaPhonist requested changes

2022-01-13 15:42 UTC, SaXaPhonist commented on backend/src/db/providers/courseProvider.ts
> +const applyCourseProvider = async (courseId: string) => {
also you should update User field "courses" to add this new one

2022-01-14 12:32 UTC, SaXaPhonist approved these changes

2022-01-14 12:58 UTC, k-krasilnikova approved these changes

2022-01-14 12:59 UTC, merged