bugfix/v1-030/my courses changed
k-krasilnikova/SUL pull request #58
Opened 2022-01-17 11:55 UTC by Julia-Maliutsina

Revised My Courses page to fit common components for Courses and My Courses page, that were changed. Made it similar to Courses page.

2022-01-17 11:59 UTC, hauteballe approved these changes

2022-01-18 10:19 UTC, k-krasilnikova requested changes

2022-01-18 10:19 UTC, k-krasilnikova commented on frontend/src/pages/MyCourses/MyCoursesList.tsx
> +import { ResponeDataType } from '../../types/responseData';
Use please absolute path, or insert an additional empty line

2022-01-18 10:19 UTC, k-krasilnikova commented on frontend/src/pages/MyCourses/MyCoursesList.tsx
> +  return (
Remove please `return` statement, no need of using it

2022-01-18 10:19 UTC, k-krasilnikova commented on frontend/src/pages/MyCourses/MyCoursesContainer.tsx
> +import MyCoursesList from './MyCoursesList';
empty line between required!

2022-01-19 10:07 UTC, hauteballe approved these changes

2022-01-19 13:59 UTC, k-krasilnikova approved these changes

2022-01-19 13:59 UTC, merged