feature-033: get course info by stage
k-krasilnikova/SUL pull request #60
Opened 2022-01-18 06:56 UTC by SaXaPhonist

- add endpoint to get course info by stage : api/course/:id/materials  api/course/:id/materials?stage=1
- add progress field to client course

2022-01-18 10:12 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-01-18 10:12 UTC, k-krasilnikova requested changes

2022-01-18 10:12 UTC, k-krasilnikova commented on backend/src/db/providers/clientCourseProvider.ts
> +  return applyedCourse;
It should be transaction!
It should be inside controller, db providers can only execute 1-2 operations with DB, but all the logic should be inside controller

2022-01-18 20:27 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-01-19 14:05 UTC, k-krasilnikova submitted a review, later dismissed

2022-01-19 14:17 UTC, merged