Feature/v1-028 Detailed course page
k-krasilnikova/SUL pull request #66
Opened 2022-01-19 15:57 UTC by hauteballe

**Overview:**
1. Implement Detailed course page with default data from constants folder
2. Implement Similar courses section with data from the server
2. Implement ProgressBar component with default data (will be changed to percentage and status from the sever )
3. Add useApplyCourse hook 
4. Button "Start the course" is redirecting to "My courses" page now (will be changed after Learning course page will be merged)
5. Fixed an issue with Help page scrollbars

2022-01-19 16:07 UTC, k-krasilnikova requested changes
Pretty good job, but some changes required!

2022-01-19 16:07 UTC, k-krasilnikova commented on frontend/src/pages/CoursesList/CoursesContainer.tsx
> +  const mutation = useApplyCourse();
```suggestion
  const { mutate, isLoading: isLoadingApplying } = useApplyCourse();
```

2022-01-19 16:07 UTC, k-krasilnikova commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +  const mutation = useApplyCourse();
We should de from the start what the props here:
```suggestion
  const { mutate, isLoading: isLoadingApplying } = useApplyCourse();
```

2022-01-19 16:07 UTC, k-krasilnikova commented on frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
> +    mutation.mutate(params._id);
Let's rename `_id` to the `courseId` around all the app

2022-01-20 09:54 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-01-20 11:53 UTC, merged