[feature/v1-053] Added new styles for Menu bar
k-krasilnikova/SUL pull request #92
Opened 2022-01-25 10:32 UTC by NikitaKhadnevich

At present this Pull request filled next changes:
1. Added _custom styles_ for selected elements;
2. Implemented function for _toggle clicked styles_;
3. _Update styles_ and created new;
4. Added _new types_ for work with this;

2022-01-26 09:11 UTC, hauteballe approved these changes

2022-01-26 11:50 UTC, Julia-Maliutsina submitted a review, later dismissed

2022-01-26 13:17 UTC, k-krasilnikova requested changes

2022-01-26 14:13 UTC, NikitaKhadnevich commented on frontend/src/api/logOut/logOut.tsx
> +          password: 'user',
No there is only mocked data for init request

2022-01-27 12:10 UTC, k-krasilnikova commented on frontend/src/api/logOut/logOut.tsx
> +          password: 'user',
Why we can't provide real data?

2022-01-27 12:15 UTC, NikitaKhadnevich commented on frontend/src/components/Layout/Menu/Menu.tsx
> +              menuItem === item.path ? { root: classes.selected } : { root: classes.default }
Resolved

2022-01-27 12:18 UTC, NikitaKhadnevich commented on frontend/src/api/logOut/logOut.tsx
> +          password: 'user',
We will implemented it in 048 task

2022-01-27 12:42 UTC, k-krasilnikova requested changes

2022-01-27 12:42 UTC, k-krasilnikova commented on frontend/src/api/logOut/logOut.tsx
> +          password: 'user',
Already merged, replace it please with endpoint from Eugene

2022-01-28 13:53 UTC, k-krasilnikova approved these changes

2022-01-28 13:53 UTC, merged